In [221]:
import pandas as pd
import seaborn as sns
import numpy as np

In [222]:
df = sns.load_dataset("titanic")
print(df.shape)
print(df.head())

(891, 15)
   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third
1         1       1  female  38.0      1      0  71.2833        C  First
2         1       3  female  26.0      0      0   7.9250        S  Third
3         1       1  female  35.0      1      0  53.1000        S  First
4         0       3    male  35.0      0      0   8.0500        S  Third

     who  adult_male deck  embark_town alive  alone
0    man        True  NaN  Southampton    no  False
1  woman       False    C    Cherbourg   yes  False
2  woman       False  NaN  Southampton   yes   True
3  woman       False    C  Southampton   yes  False
4    man        True  NaN  Southampton    no   True

In [223]:
age_col = df["age"]
print(type(age_col))
print(age_col.shape)

print(age_col.values)
print(type(age_col.values))

<class 'pandas.Series'>
(891,)
[22.   38.   26.   35.   35.     nan 54.    2.   27.   14.    4.   58.
 20.   39.   14.   55.    2.     nan 31.     nan 35.   34.   15.   28.
  8.   38.     nan 19.     nan   nan 40.     nan   nan 66.   28.   42.
   nan 21.   18.   14.   40.   27.     nan  3.   19.     nan   nan   nan
   nan 18.    7.   21.   49.   29.   65.     nan 21.   28.5   5.   11.
 22.   38.   45.    4.     nan   nan 29.   19.   17.   26.   32.   16.
 21.   26.   32.   25.     nan   nan  0.83 30.   22.   29.     nan 28.
 17.   33.   16.     nan 23.   24.   29.   20.   46.   26.   59.     nan
 71.   23.   34.   34.   28.     nan 21.   33.   37.   28.   21.     nan
 38.     nan 47.   14.5  22.   20.   17.   21.   70.5  29.   24.    2.
 21.     nan 32.5  32.5  54.   12.     nan 24.     nan 45.   33.   20.
 47.   29.   25.   23.   19.   37.   16.   24.     nan 22.   24.   19.
 18.   19.   27.    9.   36.5  42.   51.   22.   55.5  40.5    nan 51.
 16.   30.     nan   nan 44.   40.   26.   17.    1.    9.     nan 45.
   nan 28.   61.    4.    1.   21.   56.   18.     nan 50.   30.   36.
   nan   nan  9.    1.    4.     nan   nan 45.   40.   36.   32.   19.
 19.    3.   44.   58.     nan 42.     nan 24.   28.     nan 34.   45.5
 18.    2.   32.   26.   16.   40.   24.   35.   22.   30.     nan 31.
 27.   42.   32.   30.   16.   27.   51.     nan 38.   22.   19.   20.5
 18.     nan 35.   29.   59.    5.   24.     nan 44.    8.   19.   33.
   nan   nan 29.   22.   30.   44.   25.   24.   37.   54.     nan 29.
 62.   30.   41.   29.     nan 30.   35.   50.     nan  3.   52.   40.
   nan 36.   16.   25.   58.   35.     nan 25.   41.   37.     nan 63.
 45.     nan  7.   35.   65.   28.   16.   19.     nan 33.   30.   22.
 42.   22.   26.   19.   36.   24.   24.     nan 23.5   2.     nan 50.
   nan   nan 19.     nan   nan  0.92   nan 17.   30.   30.   24.   18.
 26.   28.   43.   26.   24.   54.   31.   40.   22.   27.   30.   22.
   nan 36.   61.   36.   31.   16.     nan 45.5  38.   16.     nan   nan
 29.   41.   45.   45.    2.   24.   28.   25.   36.   24.   40.     nan
  3.   42.   23.     nan 15.   25.     nan 28.   22.   38.     nan   nan
 40.   29.   45.   35.     nan 30.   60.     nan   nan 24.   25.   18.
 19.   22.    3.     nan 22.   27.   20.   19.   42.    1.   32.   35.
   nan 18.    1.   36.     nan 17.   36.   21.   28.   23.   24.   22.
 31.   46.   23.   28.   39.   26.   21.   28.   20.   34.   51.    3.
 21.     nan   nan   nan 33.     nan 44.     nan 34.   18.   30.   10.
   nan 21.   29.   28.   18.     nan 28.   19.     nan 32.   28.     nan
 42.   17.   50.   14.   21.   24.   64.   31.   45.   20.   25.   28.
   nan  4.   13.   34.    5.   52.   36.     nan 30.   49.     nan 29.
 65.     nan 50.     nan 48.   34.   47.   48.     nan 38.     nan 56.
   nan  0.75   nan 38.   33.   23.   22.     nan 34.   29.   22.    2.
  9.     nan 50.   63.   25.     nan 35.   58.   30.    9.     nan 21.
 55.   71.   21.     nan 54.     nan 25.   24.   17.   21.     nan 37.
 16.   18.   33.     nan 28.   26.   29.     nan 36.   54.   24.   47.
 34.     nan 36.   32.   30.   22.     nan 44.     nan 40.5  50.     nan
 39.   23.    2.     nan 17.     nan 30.    7.   45.   30.     nan 22.
 36.    9.   11.   32.   50.   64.   19.     nan 33.    8.   17.   27.
   nan 22.   22.   62.   48.     nan 39.   36.     nan 40.   28.     nan
   nan 24.   19.   29.     nan 32.   62.   53.   36.     nan 16.   19.
 34.   39.     nan 32.   25.   39.   54.   36.     nan 18.   47.   60.
 22.     nan 35.   52.   47.     nan 37.   36.     nan 49.     nan 49.
 24.     nan   nan 44.   35.   36.   30.   27.   22.   40.   39.     nan
   nan   nan 35.   24.   34.   26.    4.   26.   27.   42.   20.   21.
 21.   61.   57.   21.   26.     nan 80.   51.   32.     nan  9.   28.
 32.   31.   41.     nan 20.   24.    2.     nan  0.75 48.   19.   56.
   nan 23.     nan 18.   21.     nan 18.   24.     nan 32.   23.   58.
 50.   40.   47.   36.   20.   32.   25.     nan 43.     nan 40.   31.
 70.   31.     nan 18.   24.5  18.   43.   36.     nan 27.   20.   14.
 60.   25.   14.   19.   18.   15.   31.    4.     nan 25.   60.   52.
 44.     nan 49.   42.   18.   35.   18.   25.   26.   39.   45.   42.
 22.     nan 24.     nan 48.   29.   52.   19.   38.   27.     nan 33.
  6.   17.   34.   50.   27.   20.   30.     nan 25.   25.   29.   11.
   nan 23.   23.   28.5  48.   35.     nan   nan   nan 36.   21.   24.
 31.   70.   16.   30.   19.   31.    4.    6.   33.   23.   48.    0.67
 28.   18.   34.   33.     nan 41.   20.   36.   16.   51.     nan 30.5
   nan 32.   24.   48.   57.     nan 54.   18.     nan  5.     nan 43.
 13.   17.   29.     nan 25.   25.   18.    8.    1.   46.     nan 16.
   nan   nan 25.   39.   49.   31.   30.   30.   34.   31.   11.    0.42
 27.   31.   39.   18.   39.   33.   26.   39.   35.    6.   30.5    nan
 23.   31.   43.   10.   52.   27.   38.   27.    2.     nan   nan  1.
   nan 62.   15.    0.83   nan 23.   18.   39.   21.     nan 32.     nan
 20.   16.   30.   34.5  17.   42.     nan 35.   28.     nan  4.   74.
  9.   16.   44.   18.   45.   51.   24.     nan 41.   21.   48.     nan
 24.   42.   27.   31.     nan  4.   26.   47.   33.   47.   28.   15.
 20.   19.     nan 56.   25.   33.   22.   28.   25.   39.   27.   19.
   nan 26.   32.  ]
<class 'numpy.ndarray'>

In [224]:
print("Last 3 rows:", df.tail(3))

print("Column names, dtypes, nonn-null counts:", df.info())

print("Numeric Column stats:", df.describe())

print(df.columns)

print(df.dtypes)

Last 3 rows:      survived  pclass     sex   age  sibsp  parch   fare embarked  class  \
888         0       3  female   NaN      1      2  23.45        S  Third
889         1       1    male  26.0      0      0  30.00        C  First
890         0       3    male  32.0      0      0   7.75        Q  Third

       who  adult_male deck  embark_town alive  alone
888  woman       False  NaN  Southampton    no  False
889    man        True    C    Cherbourg   yes   True
890    man        True  NaN   Queenstown    no   True
<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    category
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    str
 13  alive        891 non-null    str
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), str(5)
memory usage: 80.7 KB
Column names, dtypes, nonn-null counts: None
Numeric Column stats:          survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200
Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='str')
survived          int64
pclass            int64
sex                 str
age             float64
sibsp             int64
parch             int64
fare            float64
embarked            str
class          category
who                 str
adult_male         bool
deck           category
embark_town         str
alive               str
alone              bool
dtype: object

In [225]:
# Series -> like a labeled NumPy array
s = pd.Series([10, 20, 30], index=["a", "b", "c"])
print(s)
print(s["b"])

data = {
    "name": ["Lucky (Sigma)", "Sayan", "Pitu (Paro)"],
    "age": [99, 18, 19],
    "score": [99, 85, 85],
}
small_df = pd.DataFrame(data)
print(small_df)
print(small_df.dtypes)

# series \
# array -

a    10
b    20
c    30
dtype: int64
20
            name  age  score
0  Lucky (Sigma)   99     99
1          Sayan   18     85
2    Pitu (Paro)   19     85
name       str
age      int64
score    int64
dtype: object

In [226]:
df = sns.load_dataset("titanic")

df.shape

df.info()
df.dtypes

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    category
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    str
 13  alive        891 non-null    str
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), str(5)
memory usage: 80.7 KB

survived          int64
pclass            int64
sex                 str
age             float64
sibsp             int64
parch             int64
fare            float64
embarked            str
class          category
who                 str
adult_male         bool
deck           category
embark_town         str
alive               str
alone              bool
dtype: object

In [227]:
df = pd.DataFrame(df)
df["survived"].sum()

np.int64(342)

In [228]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [229]:
print(f"Survival Rate {round(df['survived'].mean() * 100, 2)}%")

Survival Rate 38.38%

In [230]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [231]:
print(df["age"].describe())
print(df["age"].mean())
print(df["fare"].mean())

count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: age, dtype: float64
29.69911764705882
32.204207968574636

In [232]:
age = df["age"]
print("\n", type(age))
age_arr = np.array(age)
print(age_arr)
print(type(age_arr))

 <class 'pandas.Series'>
[22.   38.   26.   35.   35.     nan 54.    2.   27.   14.    4.   58.
 20.   39.   14.   55.    2.     nan 31.     nan 35.   34.   15.   28.
  8.   38.     nan 19.     nan   nan 40.     nan   nan 66.   28.   42.
   nan 21.   18.   14.   40.   27.     nan  3.   19.     nan   nan   nan
   nan 18.    7.   21.   49.   29.   65.     nan 21.   28.5   5.   11.
 22.   38.   45.    4.     nan   nan 29.   19.   17.   26.   32.   16.
 21.   26.   32.   25.     nan   nan  0.83 30.   22.   29.     nan 28.
 17.   33.   16.     nan 23.   24.   29.   20.   46.   26.   59.     nan
 71.   23.   34.   34.   28.     nan 21.   33.   37.   28.   21.     nan
 38.     nan 47.   14.5  22.   20.   17.   21.   70.5  29.   24.    2.
 21.     nan 32.5  32.5  54.   12.     nan 24.     nan 45.   33.   20.
 47.   29.   25.   23.   19.   37.   16.   24.     nan 22.   24.   19.
 18.   19.   27.    9.   36.5  42.   51.   22.   55.5  40.5    nan 51.
 16.   30.     nan   nan 44.   40.   26.   17.    1.    9.     nan 45.
   nan 28.   61.    4.    1.   21.   56.   18.     nan 50.   30.   36.
   nan   nan  9.    1.    4.     nan   nan 45.   40.   36.   32.   19.
 19.    3.   44.   58.     nan 42.     nan 24.   28.     nan 34.   45.5
 18.    2.   32.   26.   16.   40.   24.   35.   22.   30.     nan 31.
 27.   42.   32.   30.   16.   27.   51.     nan 38.   22.   19.   20.5
 18.     nan 35.   29.   59.    5.   24.     nan 44.    8.   19.   33.
   nan   nan 29.   22.   30.   44.   25.   24.   37.   54.     nan 29.
 62.   30.   41.   29.     nan 30.   35.   50.     nan  3.   52.   40.
   nan 36.   16.   25.   58.   35.     nan 25.   41.   37.     nan 63.
 45.     nan  7.   35.   65.   28.   16.   19.     nan 33.   30.   22.
 42.   22.   26.   19.   36.   24.   24.     nan 23.5   2.     nan 50.
   nan   nan 19.     nan   nan  0.92   nan 17.   30.   30.   24.   18.
 26.   28.   43.   26.   24.   54.   31.   40.   22.   27.   30.   22.
   nan 36.   61.   36.   31.   16.     nan 45.5  38.   16.     nan   nan
 29.   41.   45.   45.    2.   24.   28.   25.   36.   24.   40.     nan
  3.   42.   23.     nan 15.   25.     nan 28.   22.   38.     nan   nan
 40.   29.   45.   35.     nan 30.   60.     nan   nan 24.   25.   18.
 19.   22.    3.     nan 22.   27.   20.   19.   42.    1.   32.   35.
   nan 18.    1.   36.     nan 17.   36.   21.   28.   23.   24.   22.
 31.   46.   23.   28.   39.   26.   21.   28.   20.   34.   51.    3.
 21.     nan   nan   nan 33.     nan 44.     nan 34.   18.   30.   10.
   nan 21.   29.   28.   18.     nan 28.   19.     nan 32.   28.     nan
 42.   17.   50.   14.   21.   24.   64.   31.   45.   20.   25.   28.
   nan  4.   13.   34.    5.   52.   36.     nan 30.   49.     nan 29.
 65.     nan 50.     nan 48.   34.   47.   48.     nan 38.     nan 56.
   nan  0.75   nan 38.   33.   23.   22.     nan 34.   29.   22.    2.
  9.     nan 50.   63.   25.     nan 35.   58.   30.    9.     nan 21.
 55.   71.   21.     nan 54.     nan 25.   24.   17.   21.     nan 37.
 16.   18.   33.     nan 28.   26.   29.     nan 36.   54.   24.   47.
 34.     nan 36.   32.   30.   22.     nan 44.     nan 40.5  50.     nan
 39.   23.    2.     nan 17.     nan 30.    7.   45.   30.     nan 22.
 36.    9.   11.   32.   50.   64.   19.     nan 33.    8.   17.   27.
   nan 22.   22.   62.   48.     nan 39.   36.     nan 40.   28.     nan
   nan 24.   19.   29.     nan 32.   62.   53.   36.     nan 16.   19.
 34.   39.     nan 32.   25.   39.   54.   36.     nan 18.   47.   60.
 22.     nan 35.   52.   47.     nan 37.   36.     nan 49.     nan 49.
 24.     nan   nan 44.   35.   36.   30.   27.   22.   40.   39.     nan
   nan   nan 35.   24.   34.   26.    4.   26.   27.   42.   20.   21.
 21.   61.   57.   21.   26.     nan 80.   51.   32.     nan  9.   28.
 32.   31.   41.     nan 20.   24.    2.     nan  0.75 48.   19.   56.
   nan 23.     nan 18.   21.     nan 18.   24.     nan 32.   23.   58.
 50.   40.   47.   36.   20.   32.   25.     nan 43.     nan 40.   31.
 70.   31.     nan 18.   24.5  18.   43.   36.     nan 27.   20.   14.
 60.   25.   14.   19.   18.   15.   31.    4.     nan 25.   60.   52.
 44.     nan 49.   42.   18.   35.   18.   25.   26.   39.   45.   42.
 22.     nan 24.     nan 48.   29.   52.   19.   38.   27.     nan 33.
  6.   17.   34.   50.   27.   20.   30.     nan 25.   25.   29.   11.
   nan 23.   23.   28.5  48.   35.     nan   nan   nan 36.   21.   24.
 31.   70.   16.   30.   19.   31.    4.    6.   33.   23.   48.    0.67
 28.   18.   34.   33.     nan 41.   20.   36.   16.   51.     nan 30.5
   nan 32.   24.   48.   57.     nan 54.   18.     nan  5.     nan 43.
 13.   17.   29.     nan 25.   25.   18.    8.    1.   46.     nan 16.
   nan   nan 25.   39.   49.   31.   30.   30.   34.   31.   11.    0.42
 27.   31.   39.   18.   39.   33.   26.   39.   35.    6.   30.5    nan
 23.   31.   43.   10.   52.   27.   38.   27.    2.     nan   nan  1.
   nan 62.   15.    0.83   nan 23.   18.   39.   21.     nan 32.     nan
 20.   16.   30.   34.5  17.   42.     nan 35.   28.     nan  4.   74.
  9.   16.   44.   18.   45.   51.   24.     nan 41.   21.   48.     nan
 24.   42.   27.   31.     nan  4.   26.   47.   33.   47.   28.   15.
 20.   19.     nan 56.   25.   33.   22.   28.   25.   39.   27.   19.
   nan 26.   32.  ]
<class 'numpy.ndarray'>

In [233]:
print(df[["age"]])  # in my output, rows  X columns
print("\n", df["age"])  # length, dtype
print(type(df["age"]))  # series
print(type(df[["age"]]))  # data frame

      age
0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
..    ...
886  27.0
887  19.0
888   NaN
889  26.0
890  32.0

[891 rows x 1 columns]

 0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64
<class 'pandas.Series'>
<class 'pandas.DataFrame'>

In [234]:
# i think it depands on the syntax, because in survival there is time in some fashion
# if we change the subject height (5'10'', 6'2'', 6'0'')
# it's average height rather than rate or height per person

df.info()  # It detect non-missing values in a data frame

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    category
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    str
 13  alive        891 non-null    str
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), str(5)
memory usage: 80.7 KB

In [235]:
missing = df.isnull().sum()
print(missing[missing > 0])

age            177
embarked         2
deck           688
embark_town      2
dtype: int64

In [236]:
data = {
    "name": ["John", "Anna", "Peter", "linda"],
    "Age": [28, 34, 29, 42],
    "City": ["New Work", "Paris", "Berlin", "London"],
    "Salary": [65000, 70000, 62000, 85000],
}

In [237]:
df = pd.DataFrame(data)
print(type(df))  # Pandas dataframe

<class 'pandas.DataFrame'>

In [238]:
col_series = df["Age"]
col_df = df[["Age"]]

print(type(col_series))  # Series
print(type(col_df))  # dataframe
print("Shapes")

print(col_series.shape)  # (4, )
print(col_df.shape)  # (4, 1)

weights = np.array([[2]])  # (1, 1)
print(weights.shape)

print("\n")
# * print(col_series @ weights)
#! Exception: Dot product shape mismatch, (4,) vs (1, 1)

print(col_df @ weights)
# :)

<class 'pandas.Series'>
<class 'pandas.DataFrame'>
Shapes
(4,)
(4, 1)
(1, 1)


    0
0  56
1  68
2  58
3  84

In [239]:
df = pd.DataFrame({"A": [1, 2, 3]})

In [240]:
df

   A
0  1
1  2
2  3

In [241]:
dates = pd.date_range("20130101", periods=6)
dates  # yyyymmdd

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[us]', freq='D')

In [ ]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)
df2.dtypes2

A           float64
B    datetime64[us]
C           float32
D             int32
E          category
F               str
dtype: object

In [243]:
df2

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [244]:
df2.dtypes

A           float64
B    datetime64[us]
C           float32
D             int32
E          category
F               str
dtype: object

In [245]:
df.head()

                   A         B         C         D
2013-01-01  0.987937 -0.149231  0.376200  2.146078
2013-01-02 -0.153386 -0.031301 -0.453666  0.199365
2013-01-03  0.471348 -1.915782 -1.294701 -0.461591
2013-01-04 -0.259560 -1.050121  1.081288 -0.133261
2013-01-05  1.086424 -1.452079 -1.473648 -0.893971

In [246]:
df.tail(3)

                   A         B         C         D
2013-01-04 -0.259560 -1.050121  1.081288 -0.133261
2013-01-05  1.086424 -1.452079 -1.473648 -0.893971
2013-01-06 -2.078892  1.884179 -0.422751 -0.834292

In [247]:
df.index

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[us]', freq='D')

In [248]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='str')

In [249]:
print(df2.to_numpy())
"""
NumPy arrays have one dtype for the entire array 
while pandas DataFrames have one dtype per column
"""

[[1.0 Timestamp('2013-01-02 00:00:00') 1.0 3 'test' 'foo']
 [1.0 Timestamp('2013-01-02 00:00:00') 1.0 3 'train' 'foo']
 [1.0 Timestamp('2013-01-02 00:00:00') 1.0 3 'test' 'foo']
 [1.0 Timestamp('2013-01-02 00:00:00') 1.0 3 'train' 'foo']]

'\nNumPy arrays have one dtype for the entire array \nwhile pandas DataFrames have one dtype per column\n'

In [250]:
df.describe()

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.008978 -0.452389 -0.364546  0.003721
std    1.165393  1.358452  0.974245  1.128837
min   -2.078892 -1.915782 -1.473648 -0.893971
25%   -0.233017 -1.351589 -1.084443 -0.741117
50%    0.158981 -0.599676 -0.438209 -0.297426
75%    0.858789 -0.060783  0.176462  0.116209
max    1.086424  1.884179  1.081288  2.146078

In [251]:
df.T

   2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A    0.987937   -0.153386    0.471348   -0.259560    1.086424   -2.078892
B   -0.149231   -0.031301   -1.915782   -1.050121   -1.452079    1.884179
C    0.376200   -0.453666   -1.294701    1.081288   -1.473648   -0.422751
D    2.146078    0.199365   -0.461591   -0.133261   -0.893971   -0.834292

In [252]:
df.sort_index(axis=1, ascending=False)

                   D         C         B         A
2013-01-01  2.146078  0.376200 -0.149231  0.987937
2013-01-02  0.199365 -0.453666 -0.031301 -0.153386
2013-01-03 -0.461591 -1.294701 -1.915782  0.471348
2013-01-04 -0.133261  1.081288 -1.050121 -0.259560
2013-01-05 -0.893971 -1.473648 -1.452079  1.086424
2013-01-06 -0.834292 -0.422751  1.884179 -2.078892

In [253]:
df.sort_values(by="B")

                   A         B         C         D
2013-01-03  0.471348 -1.915782 -1.294701 -0.461591
2013-01-05  1.086424 -1.452079 -1.473648 -0.893971
2013-01-04 -0.259560 -1.050121  1.081288 -0.133261
2013-01-01  0.987937 -0.149231  0.376200  2.146078
2013-01-02 -0.153386 -0.031301 -0.453666  0.199365
2013-01-06 -2.078892  1.884179 -0.422751 -0.834292

In [254]:
df["A"]

2013-01-01    0.987937
2013-01-02   -0.153386
2013-01-03    0.471348
2013-01-04   -0.259560
2013-01-05    1.086424
2013-01-06   -2.078892
Freq: D, Name: A, dtype: float64

In [255]:
df.A  # alternate

2013-01-01    0.987937
2013-01-02   -0.153386
2013-01-03    0.471348
2013-01-04   -0.259560
2013-01-05    1.086424
2013-01-06   -2.078892
Freq: D, Name: A, dtype: float64

In [256]:
df[["B", "A"]]

                   B         A
2013-01-01 -0.149231  0.987937
2013-01-02 -0.031301 -0.153386
2013-01-03 -1.915782  0.471348
2013-01-04 -1.050121 -0.259560
2013-01-05 -1.452079  1.086424
2013-01-06  1.884179 -2.078892

In [257]:
df[0:3]

                   A         B         C         D
2013-01-01  0.987937 -0.149231  0.376200  2.146078
2013-01-02 -0.153386 -0.031301 -0.453666  0.199365
2013-01-03  0.471348 -1.915782 -1.294701 -0.461591

In [258]:
df["20130102":"20130104"]

                   A         B         C         D
2013-01-02 -0.153386 -0.031301 -0.453666  0.199365
2013-01-03  0.471348 -1.915782 -1.294701 -0.461591
2013-01-04 -0.259560 -1.050121  1.081288 -0.133261

In [259]:
df.loc[dates[0]]

A    0.987937
B   -0.149231
C    0.376200
D    2.146078
Name: 2013-01-01 00:00:00, dtype: float64

In [260]:
df.loc[:, ["A", "B"]]

                   A         B
2013-01-01  0.987937 -0.149231
2013-01-02 -0.153386 -0.031301
2013-01-03  0.471348 -1.915782
2013-01-04 -0.259560 -1.050121
2013-01-05  1.086424 -1.452079
2013-01-06 -2.078892  1.884179

In [261]:
df.loc["20130102":"20130104", ["A", "B"]] # both endpoints are included

                   A         B
2013-01-02 -0.153386 -0.031301
2013-01-03  0.471348 -1.915782
2013-01-04 -0.259560 -1.050121

In [262]:
df.loc[dates[0], "A"]

np.float64(0.9879366491805323)